import { defineDesignSystem } from "@prism-system/ui-core";
import {
  Alert,
  Avatar,
  Badge,
  Breadcrumbs,
  Button,
  Card,
  Checkbox,
  Center,
  Cluster,
  AspectRatio,
  Combobox,
  Container,
  DatePicker,
  Dialog,
  DropdownMenu,
  EmptyState,
  FileUpload,
  FormField,
  Heading,
  Input,
  Link,
  Metric,
  NumberField,
  RadioGroup,
  Section,
  Select,
  Separator,
  Skeleton,
  Sidebar,
  Slider,
  Stack,
  Switch,
  Tabs,
  Text,
  Textarea,
  Timeline,
  Toast,
  Tooltip,
} from "./components/index.js";

/**
 * Canonical runtime map for System B.
 *
 * The twenty-nine required components plus exactly the optional capabilities
 * this system implements: `Section`, `Alert`, `Skeleton`, `Toast`, `Avatar`,
 * `Breadcrumbs`, `Metric`, `Timeline`, and `EmptyState`. Omitted optional
 * components are simply unavailable; there are no empty stubs. The component
 * map mirrors `design-system.source.json`.
 */
export const DesignSystem = defineDesignSystem({
  id: "system-b",
  name: "System B",
  packageName: "@prism-system/ui-system-b",
  version: "3.0.0",
  contractVersion: 4,
  components: {
    Button,
    Input,
    Textarea,
    Card,
    Badge,
    Checkbox,
    RadioGroup,
    Switch,
    Select,
    Tabs,
    Dialog,
    DropdownMenu,
    Tooltip,
    Separator,
    Heading,
    Text,
    Link,
    Container,
    Stack,
    FormField,
    Center,
    Cluster,
    Sidebar,
    AspectRatio,
    Combobox,
    DatePicker,
    NumberField,
    Slider,
    FileUpload,
    Section,
    Alert,
    Skeleton,
    Toast,
    Avatar,
    Breadcrumbs,
    Metric,
    Timeline,
    EmptyState,
  },
  meta: {
    description: "A contrasty, expressive system with electric accents and physical motion.",
    design: {
      density: "compact",
      theme: "dark-first",
      radius: "small",
      keywords: ["dark-first", "high-contrast", "expressive", "editorial", "physical motion"],
    },
    rules: {
      allowArbitraryColors: false,
      allowArbitraryRadius: false,
      allowArbitraryShadows: false,
      allowPrimitiveDuplication: false,
    },
  },
});
export type DesignSystem = typeof DesignSystem;
