// @prism-system:tool-owned
// Generated by scripts/sync-design-system-apps.mjs from each registered system's source descriptor.
// Do not edit by hand; run `pnpm ds:register <id>` to regenerate.

/** The runtime module namespace of one declared design-system extension. */
export type ExtensionModule = Record<string, unknown>;

/** A loader that imports one declared extension module on demand. */
type ExtensionLoader = () => Promise<unknown>;

/** All declared extension loaders for one design system, keyed by name. */
type SystemExtensionLoaders = Readonly<Record<string, ExtensionLoader>>;

/**
 * Literal dynamic imports keyed by design-system id and declared extension
 * name. No module is loaded until `loadExtension` selects it.
 */
const extensionLoaders: Readonly<Record<string, SystemExtensionLoaders>> = {
  "system-b": {
    InteractiveWorkflowMap: () =>
      import("@prism-system/ui-system-b/custom/interactive-workflow-map"),
    KeyboardScene: () => import("@prism-system/ui-system-b/custom/keyboard-scene"),
  },
};

/**
 * Load one declared extension of a registered design system.
 *
 * Only the `(systemId, name)` pairs declared by the registered systems'
 * validated source descriptors resolve; anything else is rejected instead of
 * guessing an import path. The selected module is imported on demand, so
 * opening one example never evaluates another extension.
 */
export async function loadExtension(systemId: string, name: string): Promise<ExtensionModule> {
  const systemLoaders = Object.prototype.hasOwnProperty.call(extensionLoaders, systemId)
    ? extensionLoaders[systemId]
    : undefined;
  const loader =
    systemLoaders !== undefined && Object.prototype.hasOwnProperty.call(systemLoaders, name)
      ? systemLoaders[name]
      : undefined;
  if (loader === undefined) {
    throw new Error(
      `Unknown extension ${JSON.stringify(name)} for design system ${JSON.stringify(systemId)}.`,
    );
  }
  const extension = (await loader()) as ExtensionModule;
  if (!(name in extension)) {
    throw new Error(
      `Design system ${JSON.stringify(systemId)} extension ${JSON.stringify(name)} did not expose that export.`,
    );
  }
  return extension;
}
