// @prism-system:tool-owned
// Generated by scripts/sync-design-system-apps.mjs from the design-system manifest.
// Do not edit by hand; run `pnpm ds:register <id>` to regenerate.

import { createDesignSystemRegistry, type DesignSystem } from "@prism-system/ui-core";
import { DesignSystem as SystemA, systemATokens } from "@prism-system/ui-system-a";
import { DesignSystem as SystemB, systemBTokens } from "@prism-system/ui-system-b";

/** A group of related token values, for example the color or motion scale. */
export type TokenGroup = Record<string, string>;

/** Token groups every registered system exposes; typography is optional. */
export type TokenSet = {
  color: TokenGroup;
  radius: TokenGroup;
  shadow: TokenGroup;
  motion: TokenGroup;
  typography?: TokenGroup;
};

/** Concrete component props from the first registered package. */
type RegisteredComponents = (typeof SystemA)["components"];

/** A registered system with its scoped UI class and token groups. */
export type RegisteredSystem = Omit<DesignSystem, "components"> & {
  components: DesignSystem["components"] & RegisteredComponents;
  uiClass: string;
  tokens: TokenSet;
};

/** Every registered system, in stable ascending id order. */
export const registeredSystems: readonly RegisteredSystem[] = [
  { ...SystemA, uiClass: "maivand-a-ui", tokens: systemATokens } as unknown as RegisteredSystem,
  { ...SystemB, uiClass: "maivand-b-ui", tokens: systemBTokens } as unknown as RegisteredSystem,
];

export const systemRegistry = createDesignSystemRegistry(
  registeredSystems as readonly DesignSystem[],
);

/** Resolve a registered system by id. Throws when the id is unknown. */
export function getRegisteredSystem(id: string): RegisteredSystem {
  return systemRegistry.require(id) as RegisteredSystem;
}
