// @prism-system:tool-owned
// Generated by scripts/sync-design-system-apps.mjs from the design-system manifest.
// Do not edit by hand; run `pnpm ds:register <id>` to regenerate.

import {
  createDesignSystemRegistry,
  type DesignSystem,
  type DesignSystemComponents,
} from "@prism-system/ui-core";
import { DesignSystem as SystemA, systemATokens } from "@prism-system/ui-system-a";
import systemAManifest from "@prism-system/ui-system-a/manifest";
import { DesignSystem as SystemB, systemBTokens } from "@prism-system/ui-system-b";
import systemBManifest from "@prism-system/ui-system-b/manifest";

/** A group of related token values, for example the color or motion scale. */
export type TokenGroup = Record<string, string>;

/** Token groups every registered system exposes; typography is optional. */
export type TokenSet = {
  color: TokenGroup;
  radius: TokenGroup;
  shadow: TokenGroup;
  motion: TokenGroup;
  typography?: TokenGroup;
};

/** One component entry of a package's generated `./manifest` metadata. */
export type RegisteredManifestComponent = {
  variants: readonly string[];
  sizes: readonly string[];
  members: readonly string[];
  description?: string;
  docs?: string;
  example?: string;
};

/** One capability category of a package's generated `./manifest` metadata. */
export type RegisteredManifestCapabilityCategory = {
  required: readonly string[];
  optional: readonly string[];
};

/**
 * The public generated `./manifest` metadata a package publishes.
 *
 * It describes the components, variants, sizes, and compound members the
 * package promises, plus the generated capability-category inventory. The
 * category membership is a reference only: the registered runtime component
 * map stays the source of truth for what actually exists. JSON imports widen
 * literals, so the metadata versions are typed as numbers.
 */
export type RegisteredManifest = {
  schemaVersion: number;
  contractVersion: number;
  id: string;
  name: string;
  package: string;
  version: string;
  components: Readonly<Record<string, RegisteredManifestComponent>>;
  capabilities: {
    categories: Readonly<Record<string, RegisteredManifestCapabilityCategory>>;
  };
};

/**
 * A registered system with its scoped UI class, token groups, and the
 * package's public generated `./manifest` metadata.
 *
 * Availability of an optional component is a runtime question answered by the
 * real component-map keys, never by this type or by the manifest.
 */
export type RegisteredSystem = Omit<DesignSystem, "components"> & {
  components: DesignSystemComponents;
  manifest: RegisteredManifest;
  uiClass: string;
  tokens: TokenSet;
};

/** Every registered system, in stable ascending id order. */
export const registeredSystems = [
  { ...SystemA, uiClass: "maivand-a-ui", tokens: systemATokens, manifest: systemAManifest },
  { ...SystemB, uiClass: "maivand-b-ui", tokens: systemBTokens, manifest: systemBManifest },
] as unknown as readonly RegisteredSystem[];

export const systemRegistry = createDesignSystemRegistry(
  registeredSystems as unknown as readonly DesignSystem[],
);

/** Resolve a registered system by id. Throws when the id is unknown. */
export function getRegisteredSystem(id: string): RegisteredSystem {
  return systemRegistry.require(id) as unknown as RegisteredSystem;
}
