// @prism-system:tool-owned
// Generated by scripts/sync-design-system-apps.mjs from the design-system manifest.
// Do not edit by hand; run `pnpm ds:register <id>` to regenerate.

import {
  createDesignSystemRegistry,
  type DesignSystem,
  type DesignSystemComponents,
} from "@prism-system/ui-core";
import { DesignSystem as SystemA, systemATokens } from "@prism-system/ui-system-a";
import systemAManifest from "@prism-system/ui-system-a/manifest";
import { DesignSystem as SystemB, systemBTokens } from "@prism-system/ui-system-b";
import systemBManifest from "@prism-system/ui-system-b/manifest";

/** A group of related token values, for example the color or motion scale. */
export type TokenGroup = Record<string, string>;

/** Token groups every registered system exposes; typography is optional. */
export type TokenSet = {
  color: TokenGroup;
  radius: TokenGroup;
  shadow: TokenGroup;
  motion: TokenGroup;
  typography?: TokenGroup;
};

/**
 * One component entry of a package's generated `./manifest` metadata.
 *
 * `effects` is declared metadata only: a missing block means effects are
 * undeclared, and no feature or renderer is ever inferred from the name.
 */
export type RegisteredManifestComponent = {
  variants: readonly string[];
  sizes: readonly string[];
  members: readonly string[];
  effects?: RegisteredManifestEffects;
  description?: string;
  docs?: string;
  example?: string;
};

/** One capability category of a package's generated `./manifest` metadata. */
export type RegisteredManifestCapabilityCategory = {
  required: readonly string[];
  optional: readonly string[];
};

/** The kind of prerequisite one public entrypoint declares. */
export type RegisteredManifestRequirementKind = "dependency" | "peer";

/** One resolved prerequisite of a package's generated `./manifest` metadata. */
export type RegisteredManifestRequirement = {
  name: string;
  kind: RegisteredManifestRequirementKind;
  range: string;
  optional: boolean;
};

/** One code entrypoint of a package's generated `./manifest` metadata. */
export type RegisteredManifestEntrypoint = {
  requirements: readonly RegisteredManifestRequirement[];
};

/** One declared visual-effect feature of a component or extension. */
export type RegisteredManifestEffectFeature = "depth" | "motion" | "3d";

/** How a declared effect is rendered. */
export type RegisteredManifestEffectRendering = "dom" | "webgl" | "mixed";

/** The static fallback a webgl or mixed effect may provide. */
export type RegisteredManifestEffectFallback = "static" | "none";

/**
 * Explicit effect metadata declared by a source descriptor. Missing means
 * undeclared: consumers must never infer effects from a component name.
 */
export type RegisteredManifestEffects = {
  features: readonly RegisteredManifestEffectFeature[];
  rendering: RegisteredManifestEffectRendering;
  reducedMotion: boolean;
  fallback?: RegisteredManifestEffectFallback;
};

/** One declared extension export of a package's generated `./manifest` metadata. */
export type RegisteredManifestExtension = {
  apiVersion: number;
  entrypoint: string;
  description: string;
  docs: string;
  example: string;
  effects?: RegisteredManifestEffects;
};

/**
 * The public generated `./manifest` metadata a package publishes.
 *
 * It describes the components, variants, sizes, and compound members the
 * package promises, the public entrypoints and their resolved prerequisite
 * requirements, and any declared extensions, plus the generated
 * capability-category inventory. Availability is catalog metadata: a shared
 * component exists when its key is present in `components`, an extension when
 * its key is present in `extensions`. The category inventory is a reference
 * only, never a second availability list. JSON imports widen literals, so the
 * metadata versions are typed as numbers.
 */
export type RegisteredManifest = {
  schemaVersion: number;
  contractVersion: number;
  id: string;
  name: string;
  package: string;
  version: string;
  entrypoints: Readonly<Record<string, RegisteredManifestEntrypoint>>;
  components: Readonly<Record<string, RegisteredManifestComponent>>;
  capabilities: {
    categories: Readonly<Record<string, RegisteredManifestCapabilityCategory>>;
  };
  extensions?: Readonly<Record<string, RegisteredManifestExtension>>;
};

/**
 * A registered system with its scoped UI class, token groups, and the
 * package's public generated `./manifest` metadata.
 *
 * Availability is the catalog metadata in `manifest` (`components` keys, and
 * extension keys in `extensions`); the runtime component map is the imported
 * implementation, not a second availability source.
 */
export type RegisteredSystem = Omit<DesignSystem, "components"> & {
  components: DesignSystemComponents;
  manifest: RegisteredManifest;
  uiClass: string;
  tokens: TokenSet;
};

/** Every registered system, in stable ascending id order. */
export const registeredSystems = [
  { ...SystemA, uiClass: "maivand-a-ui", tokens: systemATokens, manifest: systemAManifest },
  { ...SystemB, uiClass: "maivand-b-ui", tokens: systemBTokens, manifest: systemBManifest },
] as unknown as readonly RegisteredSystem[];

export const systemRegistry = createDesignSystemRegistry(
  registeredSystems as unknown as readonly DesignSystem[],
);

/** Resolve a registered system by id. Throws when the id is unknown. */
export function getRegisteredSystem(id: string): RegisteredSystem {
  return systemRegistry.require(id) as unknown as RegisteredSystem;
}
