import { defineDesignSystem } from "@prism-system/ui-core";
import {
  Accordion,
  AspectRatio,
  Alert,
  Badge,
  Button,
  Card,
  Center,
  Checkbox,
  Cluster,
  Combobox,
  Container,
  DatePicker,
  DescriptionList,
  Dialog,
  DropdownMenu,
  FileUpload,
  Fieldset,
  FormField,
  Grid,
  Heading,
  Input,
  Link,
  Meter,
  Metric,
  NumberField,
  Pagination,
  Progress,
  RadioGroup,
  Select,
  Separator,
  Sidebar,
  Slider,
  Stack,
  Switch,
  Table,
  Tabs,
  Text,
  Textarea,
  Timeline,
  Tooltip,
} from "./components/index.js";

/**
 * Canonical runtime map for System A.
 *
 * The twenty-nine required components are always present; the optional components
 * below are capabilities System A actually implements (Grid, Fieldset, Alert,
 * Progress, Accordion, Pagination, Table, Metric, DescriptionList, Meter, and
 * Timeline). Any other optional name is intentionally absent and therefore
 * unavailable.
 */
export const DesignSystem = defineDesignSystem({
  id: "system-a",
  name: "System A",
  packageName: "@prism-system/ui-system-a",
  version: "2.0.0",
  contractVersion: 4,
  components: {
    Button,
    Input,
    Textarea,
    Card,
    Badge,
    Checkbox,
    RadioGroup,
    Switch,
    Select,
    Tabs,
    Dialog,
    DropdownMenu,
    Tooltip,
    Separator,
    Heading,
    Text,
    Link,
    Container,
    Stack,
    FormField,
    Center,
    Cluster,
    Sidebar,
    AspectRatio,
    Combobox,
    DatePicker,
    NumberField,
    Slider,
    FileUpload,
    Grid,
    Fieldset,
    Alert,
    Progress,
    Accordion,
    Pagination,
    Table,
    Metric,
    DescriptionList,
    Meter,
    Timeline,
  },
  meta: {
    description: "A calm, focused visual system with warm surfaces and quiet rhythm.",
    design: {
      density: "comfortable",
      theme: "light-first",
      radius: "small",
      keywords: [
        "calm",
        "minimal",
        "editorial",
        "warm light surfaces",
        "ink-led hierarchy",
        "quiet borders",
        "restrained motion",
        "low visual noise",
      ],
    },
    rules: {
      allowArbitraryColors: false,
      allowArbitraryRadius: false,
      allowArbitraryShadows: false,
      allowPrimitiveDuplication: false,
    },
  },
});
export type DesignSystem = typeof DesignSystem;
