#!/usr/bin/env node
/**
 * V2/V4 app registry generation tests (Node built-in test runner, no
 * dependency).
 *
 * Run directly:
 *   node --test scripts/sync-design-system-apps.test.mjs
 *
 * These exercise the real generator path (`planAppIntegration`) rather than a
 * test-only reimplementation:
 *
 *   - the V2-only case is a byte-for-byte golden proving the original V2 output
 *     is unchanged and never imports a V4 manifest;
 *   - the mixed and V4-only cases prove V2 and V4 stay discriminated, the full
 *     runtime V4 component map is exposed through the public
 *     `DesignSystemComponentsV4`/`DesignSystemV4` types, each V4 entry carries
 *     its package's public generated `./manifest` metadata, and no optional
 *     component is fabricated or guessed from a name list;
 *   - the live `config/design-systems.json` is projected into both apps and the
 *     committed Showcase and Reference App registries are checked against that
 *     plan, so both stay byte-identical and in sync.
 */

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";

import { planAppIntegration } from "./sync-design-system-apps.mjs";
import { readManifest } from "./register-design-system.mjs";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

/**
 * The canonical V4 names, mirroring `@prism-system/ui-core`. The registry
 * generator must never enumerate either set: the twenty required names come
 * from `DesignSystemComponentsV4`, and optional presence comes from the real
 * runtime component-map keys.
 */
const REQUIRED_V4_NAMES = [
  "Button",
  "Input",
  "Textarea",
  "Card",
  "Badge",
  "Checkbox",
  "RadioGroup",
  "Switch",
  "Select",
  "Tabs",
  "Dialog",
  "DropdownMenu",
  "Tooltip",
  "Separator",
  "Heading",
  "Text",
  "Link",
  "Container",
  "Stack",
  "FormField",
];

const OPTIONAL_V4_NAMES = [
  "Grid",
  "Section",
  "Fieldset",
  "Alert",
  "Progress",
  "Skeleton",
  "Toast",
  "Accordion",
  "Avatar",
  "Breadcrumbs",
  "Pagination",
  "Table",
];

function entry(overrides) {
  return { version: "0.1.0", ...overrides };
}

function manifest(...systems) {
  return { version: 2, designSystems: systems };
}

async function registrySourceFor(manifestValue, app = "showcase") {
  const plan = await planAppIntegration({ manifest: manifestValue, root: repoRoot });
  assert.equal(plan.status, "planned");
  const file = plan.files.find(
    (candidate) => candidate.kind === "registry" && candidate.app === app,
  );
  assert.ok(file, `registry file planned for ${app}`);
  return file.after;
}

/** The `const v2Systems = [...]` / `const v4Systems = [...]` registration blocks. */
function systemBlocks(source) {
  const v2 = source.slice(
    source.indexOf("const v2Systems = ["),
    source.indexOf("] as unknown as readonly DesignSystem[];"),
  );
  const v4 = source.slice(
    source.indexOf("const v4Systems = ["),
    source.indexOf("] as unknown as readonly DesignSystemV4[];"),
  );
  assert.notEqual(v2, "", "v2Systems registration block exists");
  assert.notEqual(v4, "", "v4Systems registration block exists");
  return { v2, v4 };
}

/** Assert that `source` never names any optional V4 component. */
function assertNoOptionalNameGuessing(source) {
  for (const name of OPTIONAL_V4_NAMES) {
    assert.doesNotMatch(
      source,
      new RegExp(`\\b${name}\\b`),
      `generated registry must not name optional component ${name}`,
    );
  }
}

const SYSTEM_A = entry({
  id: "system-a",
  name: "System A",
  packageName: "@prism-system/ui-system-a",
  packagePath: "packages/system-a",
  version: "1.1.0",
  uiClass: "maivand-a-ui",
  tokensExport: "systemATokens",
  contract: "v2",
});

const SYSTEM_B = entry({
  id: "system-b",
  name: "System B",
  packageName: "@prism-system/ui-system-b",
  packagePath: "packages/system-b",
  version: "1.1.0",
  uiClass: "maivand-b-ui",
  tokensExport: "systemBTokens",
  contract: "v2",
});

const PULSE_V4 = entry({
  id: "pulse",
  name: "Pulse",
  packageName: "@prism-system/ui-pulse",
  packagePath: "packages/pulse",
  uiClass: "maivand-pulse-ui",
  tokensExport: "pulseTokens",
  contract: "v4",
});

/**
 * The frozen V2-only registry output (the original generator shape, committed
 * before V4 support). It is a literal so the V2 path stays byte-for-byte
 * reproducible without depending on the current app checkouts.
 */
const V2_REGISTRY_GOLDEN = [
  "// @prism-system:tool-owned",
  "// Generated by scripts/sync-design-system-apps.mjs from the design-system manifest.",
  "// Do not edit by hand; run `pnpm ds:register <id>` to regenerate.",
  "",
  'import { createDesignSystemRegistry, type DesignSystem } from "@prism-system/ui-core";',
  'import { DesignSystem as SystemA, systemATokens } from "@prism-system/ui-system-a";',
  'import { DesignSystem as SystemB, systemBTokens } from "@prism-system/ui-system-b";',
  "",
  "/** A group of related token values, for example the color or motion scale. */",
  "export type TokenGroup = Record<string, string>;",
  "",
  "/** Token groups every registered system exposes; typography is optional. */",
  "export type TokenSet = {",
  "  color: TokenGroup;",
  "  radius: TokenGroup;",
  "  shadow: TokenGroup;",
  "  motion: TokenGroup;",
  "  typography?: TokenGroup;",
  "};",
  "",
  "/** Concrete component props from the first registered package. */",
  'type RegisteredComponents = (typeof SystemA)["components"];',
  "",
  "/** A registered system with its scoped UI class and token groups. */",
  'export type RegisteredSystem = Omit<DesignSystem, "components"> & {',
  '  components: DesignSystem["components"] & RegisteredComponents;',
  "  uiClass: string;",
  "  tokens: TokenSet;",
  "};",
  "",
  "/** Every registered system, in stable ascending id order. */",
  "export const registeredSystems: readonly RegisteredSystem[] = [",
  '  { ...SystemA, uiClass: "maivand-a-ui", tokens: systemATokens } as unknown as RegisteredSystem,',
  '  { ...SystemB, uiClass: "maivand-b-ui", tokens: systemBTokens } as unknown as RegisteredSystem,',
  "];",
  "",
  "export const systemRegistry = createDesignSystemRegistry(",
  "  registeredSystems as readonly DesignSystem[],",
  ");",
  "",
  "/** Resolve a registered system by id. Throws when the id is unknown. */",
  "export function getRegisteredSystem(id: string): RegisteredSystem {",
  "  return systemRegistry.require(id) as RegisteredSystem;",
  "}",
  "",
].join("\n");

test("a V2-only manifest reproduces the V2-only registry golden exactly", async () => {
  const source = await registrySourceFor(manifest(SYSTEM_A, SYSTEM_B));
  assert.equal(source, V2_REGISTRY_GOLDEN);
  // The V2 path never emits the V4 registry, the mixed contract union, or a
  // package manifest import.
  assert.doesNotMatch(source, /createDesignSystemRegistryV4/);
  assert.doesNotMatch(source, /componentContract: "v2" \| "v4"/);
  assert.doesNotMatch(source, /\/manifest/);
  assert.doesNotMatch(source, /RegisteredSystemV4/);
});

test("a mixed V2/V4 manifest discriminates the contracts and exposes the V4 map + manifest", async () => {
  const source = await registrySourceFor(manifest(SYSTEM_A, PULSE_V4));

  // Each contract keeps its own runtime guard and its real contract.
  assert.match(source, /createDesignSystemRegistry\(v2Systems\)/);
  assert.match(source, /createDesignSystemRegistryV4\(v4Systems\)/);
  // The generator never assigns a contract marker: the package values carry it.
  assert.doesNotMatch(source, /componentContract\s*:/);
  assert.doesNotMatch(source, /componentContract:\s*"v2"\s*[,;]/);

  // V2 and V4 are separate, discriminated entry types; no V2 cast as V4.
  assert.match(source, /export type RegisteredSystemV2 = Omit<DesignSystem, "components"> & \{/);
  assert.match(source, /export type RegisteredSystemV4 = Omit<DesignSystemV4, "components"> & \{/);
  assert.match(source, /export type RegisteredSystem = RegisteredSystemV2 \| RegisteredSystemV4;/);

  // The full V4 runtime map is exposed through the public core V4 types; the
  // surface is no longer limited to the fourteen shared names.
  assert.match(
    source,
    /import \{\n  createDesignSystemRegistry,\n  createDesignSystemRegistryV4,\n  type DesignSystem,\n  type DesignSystemComponentsV4,\n  type DesignSystemV4,\n\} from "@prism-system\/ui-core";/,
  );
  assert.match(
    source,
    /type RegisteredComponentsV4 = DesignSystemComponentsV4 & Partial<\(typeof Pulse\)\["components"\]>;/,
  );
  assert.match(source, /components: RegisteredComponentsV4;/);
  assert.match(source, /manifest: RegisteredManifest;/);
  assert.doesNotMatch(source, /SharedComponentName/);
  assert.doesNotMatch(source, /Pick<\(typeof Pulse\)\["components"\]/);

  // The package's public generated manifest metadata is imported and carried.
  assert.match(source, /import pulseManifest from "@prism-system\/ui-pulse\/manifest";/);
  assert.match(source, /export type RegisteredManifestComponent = \{/);
  assert.match(source, /variants: readonly string\[\];/);
  assert.match(source, /members: readonly string\[\];/);
  assert.match(source, /components: Readonly<Record<string, RegisteredManifestComponent>>;/);

  assert.ok(source.includes('"@prism-system/ui-system-a"'));
  assert.ok(source.includes('"@prism-system/ui-pulse"'));
  // The V2 package ships no generated V4 manifest; none is imported for it.
  assert.doesNotMatch(source, /@prism-system\/ui-system-a\/manifest/);
  assert.doesNotMatch(source, /systemAManifest/);

  const { v2, v4 } = systemBlocks(source);
  assert.match(v2, /\.\.\.SystemA/);
  assert.doesNotMatch(v2, /\.\.\.Pulse/);
  assert.doesNotMatch(v2, /manifest/);
  assert.match(v4, /\.\.\.Pulse/);
  assert.match(v4, /manifest: pulseManifest/);
  assert.doesNotMatch(v4, /\.\.\.SystemA/);

  // Optional presence is never fabricated or guessed: the registrations spread
  // the package's actual runtime map and no component is enumerated, and no
  // optional V4 name appears anywhere in the generated source.
  for (const name of [...REQUIRED_V4_NAMES, ...OPTIONAL_V4_NAMES]) {
    assert.doesNotMatch(v4, new RegExp(`\\b${name}\\b`));
  }
  assertNoOptionalNameGuessing(source);
});

test("a V4-only manifest keeps both registries and an empty V2 set", async () => {
  const source = await registrySourceFor(manifest(PULSE_V4));

  assert.match(source, /const v2Systems = \[\]/);
  assert.match(source, /const v4Systems = \[/);
  assert.match(source, /\.\.\.Pulse/);
  assert.match(source, /createDesignSystemRegistry\(v2Systems\)/);
  assert.match(source, /createDesignSystemRegistryV4\(v4Systems\)/);

  // V4-only output still exposes the full V4 map and the package manifest.
  assert.match(
    source,
    /type RegisteredComponentsV4 = DesignSystemComponentsV4 & Partial<\(typeof Pulse\)\["components"\]>;/,
  );
  assert.match(source, /import pulseManifest from "@prism-system\/ui-pulse\/manifest";/);
  assert.match(source, /manifest: RegisteredManifest;/);
  assert.doesNotMatch(source, /SharedComponentName/);
  assertNoOptionalNameGuessing(source);
});

test("an unsupported contract is rejected instead of normalized", async () => {
  await assert.rejects(
    planAppIntegration({
      manifest: manifest(
        entry({
          id: "legacy",
          name: "Legacy",
          packageName: "@prism-system/ui-legacy",
          packagePath: "packages/legacy",
          uiClass: "maivand-legacy-ui",
          tokensExport: "legacyTokens",
          contract: "v1",
        }),
      ),
      root: repoRoot,
    }),
    /contract "v1"/,
  );
});

/* -------------------------------------------------------------------------- */
/* Live repository integration                                                 */
/* -------------------------------------------------------------------------- */

const liveManifest = readManifest({
  manifestPath: join(repoRoot, "config", "design-systems.json"),
});

test("the committed Showcase and Reference App registries match the generated plan", async () => {
  const plan = await planAppIntegration({ manifest: liveManifest, root: repoRoot });
  assert.equal(plan.status, "planned");

  const registries = plan.files.filter((file) => file.kind === "registry");
  assert.deepEqual(
    registries.map((file) => file.app),
    ["showcase", "reference-app"],
  );
  const [showcase, reference] = registries;
  assert.equal(showcase.after, reference.after, "both apps generate the same registry");

  for (const file of registries) {
    assert.equal(file.action, "unchanged", `${file.relativePath} is in sync`);
    assert.equal(
      readFileSync(file.path, "utf8"),
      file.after,
      `${file.relativePath} matches the generated plan`,
    );
  }
});

test("the live registries expose every V4 package manifest and no guessed capability", async () => {
  const v4Entries = liveManifest.designSystems.filter((entry) => entry.contract === "v4");
  const v2Entries = liveManifest.designSystems.filter((entry) => entry.contract === "v2");
  assert.ok(v4Entries.length > 0, "the live manifest registers at least one V4 system");

  const source = await registrySourceFor(liveManifest);

  // The full V4 required surface comes from the public core V4 map.
  assert.match(
    source,
    /type RegisteredComponentsV4 = DesignSystemComponentsV4 & Partial<\(typeof \w+\)\["components"\]>;/,
  );
  assert.match(source, /export type RegisteredSystemV4 = Omit<DesignSystemV4, "components"> & \{/);

  for (const system of v4Entries) {
    const alias = system.id
      .split("-")
      .filter(Boolean)
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join("");
    const manifestAlias = `${alias.charAt(0).toLowerCase()}${alias.slice(1)}Manifest`;

    // The generated registry consumes the package's own public `./manifest`.
    assert.ok(
      source.includes(
        `import ${manifestAlias} from ${JSON.stringify(`${system.packageName}/manifest`)};`,
      ),
      `${system.packageName}/manifest is imported`,
    );
    assert.ok(source.includes(`manifest: ${manifestAlias}`), `${system.id} carries its manifest`);

    // The shipped manifest declares exactly the twenty required V4 names plus
    // optional names only — the metadata is the package's, not a copy.
    const shipped = JSON.parse(
      readFileSync(join(repoRoot, system.packagePath, "design-system.json"), "utf8"),
    );
    assert.equal(shipped.contract, "v4");
    assert.equal(shipped.package, system.packageName);
    assert.equal(shipped.version, system.version);
    for (const name of REQUIRED_V4_NAMES) {
      assert.ok(
        Object.prototype.hasOwnProperty.call(shipped.components, name),
        `${system.id} manifest declares required ${name}`,
      );
    }
    for (const name of Object.keys(shipped.components)) {
      assert.ok(
        REQUIRED_V4_NAMES.includes(name) || OPTIONAL_V4_NAMES.includes(name),
        `${system.id} manifest declares only known V4 names (saw ${name})`,
      );
    }
  }

  // No V2 package manifest is imported, and no optional name is guessed
  // anywhere in the generated source.
  for (const system of v2Entries) {
    assert.ok(!source.includes(`${system.packageName}/manifest`));
  }
  assertNoOptionalNameGuessing(source);
});
